// Images - Icons
import favicon from './images/icons/favicon.ico';
import favicon16 from './images/icons/favicon-16x16.png';
import favicon32 from './images/icons/favicon-32x32.png';
import favicon96 from './images/icons/favicon-96x96.png';
import android36 from './images/icons/android-icon-36x36.png';
import android48 from './images/icons/android-icon-48x48.png';
import android72 from './images/icons/android-icon-72x72.png';
import android96 from './images/icons/android-icon-96x96.png';
import android144 from './images/icons/android-icon-144x144.png';
import android192 from './images/icons/android-icon-192x192.png';
import apple from './images/icons/apple-icon.png';
import appleprecompressed from './images/icons/apple-icon-precomposed.png';
import apple57 from './images/icons/apple-icon-57x57.png';
import apple60 from './images/icons/apple-icon-60x60.png';
import apple72 from './images/icons/apple-icon-72x72.png';
import apple76 from './images/icons/apple-icon-76x76.png';
import apple114 from './images/icons/apple-icon-114x114.png';
import apple120 from './images/icons/apple-icon-120x120.png';
import apple144 from './images/icons/apple-icon-144x144.png';
import apple152 from './images/icons/apple-icon-152x152.png';
import apple180 from './images/icons/apple-icon-180x180.png';
import ms70 from './images/icons/ms-icon-70x70.png';
import ms144 from './images/icons/ms-icon-144x144.png';
import ms150 from './images/icons/ms-icon-150x150.png';
import ms310 from './images/icons/ms-icon-310x310.png';

// Images - Global
import feature from './images/feature.jpg';
import sun from './images/icons/sun.svg';
import moon from './images/icons/moon.svg';

// Images - Homepage
import mask from './images/facemask.png';
import nomask from './images/nomask.png';

// Images - Blog
import zerotowordpress from './images/posts/0-to-wordpress-in-4-minutes/zerotowordpress.jpg';
import zerotowordpressretina from './images/posts/0-to-wordpress-in-4-minutes/zerotowordpress@2x.jpg';
import acompleteguidetoeleventy from './images/posts/a-complete-guide-to-eleventy/acompleteguidetoeleventy.jpg';
import acompleteguidetoeleventyretina from './images/posts/a-complete-guide-to-eleventy/acompleteguidetoeleventy@2x.jpg';
import conistonwatertwentytwenty from './images/posts/coniston-water-2020/conistonwater2020.jpg';
import conistonwatertwentytwentyretina from './images/posts/coniston-water-2020/conistonwater2020@2x.jpg';
import conistonwatertwentytwenty01 from './images/posts/coniston-water-2020/conistonwater2020-1.jpg';
import conistonwatertwentytwenty01retina from './images/posts/coniston-water-2020/conistonwater2020-1@2x.jpg';
import conistonwatertwentytwenty02 from './images/posts/coniston-water-2020/conistonwater2020-2.jpg';
import conistonwatertwentytwenty02retina from './images/posts/coniston-water-2020/conistonwater2020-2@2x.jpg';
import conistonwatertwentytwenty03 from './images/posts/coniston-water-2020/conistonwater2020-3.jpg';
import conistonwatertwentytwenty03retina from './images/posts/coniston-water-2020/conistonwater2020-3@2x.jpg';
import conistonwatertwentytwenty04 from './images/posts/coniston-water-2020/conistonwater2020-4.jpg';
import conistonwatertwentytwenty04retina from './images/posts/coniston-water-2020/conistonwater2020-4@2x.jpg';
import conistonwatertwentytwenty05 from './images/posts/coniston-water-2020/conistonwater2020-5.jpg';
import conistonwatertwentytwenty05retina from './images/posts/coniston-water-2020/conistonwater2020-5@2x.jpg';
import conistonwatertwentytwenty06 from './images/posts/coniston-water-2020/conistonwater2020-6.jpg';
import conistonwatertwentytwenty06retina from './images/posts/coniston-water-2020/conistonwater2020-6@2x.jpg';
import conistonwatertwentytwenty07 from './images/posts/coniston-water-2020/conistonwater2020-7.jpg';
import conistonwatertwentytwenty07retina from './images/posts/coniston-water-2020/conistonwater2020-7@2x.jpg';
import beingawomanintechsucks from './images/posts/being-a-woman-in-tech-sucks/beingawomanintechsucks.jpg';
import beingawomanintechsucksretina from './images/posts/being-a-woman-in-tech-sucks/beingawomanintechsucks@2x.jpg';
import marissamayer from './images/posts/being-a-woman-in-tech-sucks/marissa-mayer.jpg';
import adviceforwebdevelopmenstudents from './images/posts/advice-for-web-developmen-students/adviceforwebdevelopmenstudents.jpg';
import adviceforwebdevelopmenstudentsretina from './images/posts/advice-for-web-developmen-students/adviceforwebdevelopmenstudents@2x.jpg';
import mentorleaving from './images/posts/how-a-mentor-leaving-can-inspire-you/mentorleaving.jpg';
import mentorleavingretina from './images/posts/how-a-mentor-leaving-can-inspire-you/mentorleaving@2x.jpg';
import gitlabpages from './images/posts/gitlab-pages/gitlabpages.jpg';
import gitlabpagesretina from './images/posts/gitlab-pages/gitlabpages@2x.jpg';
import wordpressify from './images/posts/wordpressify/wordpressify.jpg';
import wordpressifyretina from './images/posts/wordpressify/wordpressify@2x.jpg';
import emailisntbroken from './images/posts/email-isnt-broken/emailisntbroken.jpg';
import emailisntbrokenretina from './images/posts/email-isnt-broken/emailisntbroken@2x.jpg';
import craftcmshomestead from './images/posts/craft-cms-and-homestead/craftcmshomestead.jpg';
import craftcmshomesteadretina from './images/posts/craft-cms-and-homestead/craftcmshomestead@2x.jpg';
import magentonginx from './images/posts/no-ccs-or-js-on-magento-2-after-install/magentonginx.jpg';
import magentonginxretina from './images/posts/no-ccs-or-js-on-magento-2-after-install/magentonginx@2x.jpg';
import githublarge from './images/posts/github-pages/githublarge.jpg';
import githublargeretina from './images/posts/github-pages/githublarge@2x.jpg';
import valetlarge from './images/posts/wordpress-valet/valetlarge.jpg';
import valetlargeretina from './images/posts/wordpress-valet/valetlarge@2x.jpg';
import eleventygithubpages from './images/posts/eleventy-github-pages/eleventygithubpages.jpg';
import eleventygithubpagesretina from './images/posts/eleventy-github-pages/eleventygithubpages@2x.jpg';
import githubactions from './images/posts/github-actions-hackathon/githubactions.jpg';
import githubactionsretina from './images/posts/github-actions-hackathon/githubactions@2x.jpg';
import projectmanagementtools from './images/posts/project-management-tools/projectmanagementtools.jpg';
import projectmanagementtoolsretina from './images/posts/project-management-tools/projectmanagementtools@2x.jpg';

// Images - Work
import townscapercommunity from './images/work/townscaper-community/townscapercommunity.jpg';
import townscapercommunityretina from './images/work/townscaper-community/townscapercommunity@2x.jpg';
import canetticodes from './images/work/canetti-codes/canetticodes.jpg';
import canetticodesretina from './images/work/canetti-codes/canetticodes@2x.jpg';
import aligngs from './images/work/align-gs/align-gs.jpg';
import aligngsretina from './images/work/align-gs/align-gs@2x.jpg';
import kbpro from './images/work/kbpro/kbpro.jpg';
import kbproretina from './images/work/kbpro/kbpro@2x.jpg';
import emeraldkitchens from './images/work/emerald-kitchens/emeraldkitchens.jpg';
import emeraldkitchensretina from './images/work/emerald-kitchens/emeraldkitchens@2x.jpg';
import marketingnewsbuilder from './images/work/mn-builder/marketing-news-builder.jpg';
import marketingnewsbuilderretina from './images/work/mn-builder/marketing-news-builder@2x.jpg';

// CSS
import './partials/main.scss';